# Copyright (c) 2025 Hemispheres Foundation
# Use of this source code is governed by the MIT License,
# which can be found in the LICENSE file.

# GitHub Actions workflow to deploy the Bitcoin Kit Demo to the production environment.
name: "Production Deployment"
on:
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: "production-deploy-${{ github.event.number || github.ref }}"
  cancel-in-progress: false

jobs:
  # Build and push Docker image
  docker:
    name: Docker
    uses: hemilabs/actions/.github/workflows/docker.yml@main
    permissions:
      contents: read
      packages: write # Needed to push to the GitHub Container Registry
    with:
      version: "${{ github.sha }}"
      context: "."
      file: "./Dockerfile"
      dockerhub: true
      tags: |
        hemilabs/bitcoin-kit:${{ github.sha }}
        ghcr.io/hemilabs/bitcoin-kit:${{ github.sha }}
      build-args: |
        BUILD_MODE=mainnet
        VITE_HEMI_BITCOIN_KIT_ANALYTICS_WEBSITE_ID=${{ vars.VITE_HEMI_BITCOIN_KIT_ANALYTICS_WEBSITE_ID }}
    secrets:
      DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
      DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_TOKEN }}"

  # Deploy to Kubernetes cluster
  deploy:
    name: Deploy to production
    uses: hemilabs/actions/.github/workflows/deploy-kustomize.yml@main
    needs:
      - docker
    permissions:
      contents: read
    with:
      namespace: "bitcoin-kit"
      kustomize: "./kubernetes/kustomize/overlays/production/"
      image: "hemilabs/bitcoin-kit:${{ github.sha }}"
      environment-name: production
      environment-url: "https://bitcoin-kit.hemi.xyz/"
    secrets:
      KUBECONFIG: "${{ secrets.APPS_PROD_KUBECONFIG }}"
      KUBECONFIG_CONTEXT: "${{ secrets.APPS_PROD_KUBECONFIG_CONTEXT }}"
